language: node_js
sudo: false
dist: xenial

node_js:
  - "8"

cache:
  directories:
    - node_modules

git:
  depth: 10

jobs:
  include:
    - stage: Static Test
      env:
        - test: Editor Config check
      install:
      - npm i -g eclint
      script:
      - eclint check
